export class Dispositivo {
	ID_DISPOSITIVO:number;
	ID_TIPO_SERVOMOTOR:number;
	ID_TIPO_BATERIA:number;
	DESCRIPCION:string;
	NUMERO_PLACA:string;
	VIDA_UTIL_MINIMA:number;
	VIDA_UTIL_MAXIMA:number;
	USUARIO_CREACION:number;
	FECHA_CREACION:string;
	USUARIO_MODIFICACION:number;
	FECHA_MODIFICACION:string;
	ESTADO_REGISTRO:boolean;
}