export class Tanque {
	ID_TIPO_TANQUE: number;
	DESCRIPCION: string;
	CAPACIDAD_MINIMA: number;
	CAPACIDAD_MAXIMA: number;
	USUARIO_CREACION: number;
	FECHA_CREACION: string;
	USUARIO_MODIFICACION:  number;
	FECHA_MODIFICACION: string;
	ESTADO_REGISTRO: string;
}